import React from "react";

const TermsOfServicePage = () => {
  return (
    <div className="container mx-auto px-4 py-8 bg-[#463125] min-h-screen">
      <h1 className="text-4xl font-bold mb-6 text-[#a07155]">
        Terms of Service
      </h1>
      <div className="prose max-w-2xl">
        <section className="mb-6">
          <h2 className="text-2xl font-semibold mb-4">User Agreement</h2>
          <p>
            By using SAGE AI, you agree to comply with and be bound by the
            following terms and conditions.
          </p>
        </section>
        <section className="mb-6">
          <h2 className="text-2xl font-semibold mb-4">Use of Service</h2>
          <p>
            SAGE AI grants you a personal, non-transferable, and non-exclusive
            right to access and use our platform.
          </p>
        </section>
        <section>
          <h2 className="text-2xl font-semibold mb-4">Intellectual Property</h2>
          <p>
            All content generated by SAGE AI is protected by intellectual
            property laws. Users retain rights to their input, while SAGE AI
            retains rights to the AI-generated content.
          </p>
        </section>
      </div>
    </div>
  );
};

export default TermsOfServicePage;
